#ifndef FLUX_TB_METRICS_H
#define FLUX_TB_METRICS_H

#define FLUX_TEXTBOX_ACTION_BUTTON_W 30.0f
#define FLUX_PASSWORD_REVEAL_BTN_W   FLUX_TEXTBOX_ACTION_BUTTON_W

#define FLUX_NUMBER_BOX_SPIN_BTN_W   32.0f
#define FLUX_NUMBER_BOX_UP_MARGIN    4.0f
#define FLUX_NUMBER_BOX_DN_MARGIN_L  0.0f
#define FLUX_NUMBER_BOX_DN_MARGIN_T  4.0f
#define FLUX_NUMBER_BOX_DN_MARGIN_R  4.0f
#define FLUX_NUMBER_BOX_DN_MARGIN_B  4.0f
#define FLUX_NUMBER_BOX_COL_UP_W     (FLUX_NUMBER_BOX_SPIN_BTN_W + FLUX_NUMBER_BOX_UP_MARGIN * 2.0f)
#define FLUX_NUMBER_BOX_COL_DN_W                                                             \
	(FLUX_NUMBER_BOX_SPIN_BTN_W + FLUX_NUMBER_BOX_DN_MARGIN_L + FLUX_NUMBER_BOX_DN_MARGIN_R)
#define FLUX_NUMBER_BOX_SPIN_W       (FLUX_NUMBER_BOX_COL_UP_W + FLUX_NUMBER_BOX_COL_DN_W)
#define FLUX_NUMBER_BOX_DELETE_BTN_W 40.0f

#endif
